package pro.sky.telegrambot.constant;

public enum TypesOfInformation {
    INFO_ABOUT_BOT,
    LONG_INFO_ABOUT_SHELTER,
    SHELTER_CONTACT_INFO,
    SHELTER_PASS_REG_INFO,
    SAFETY_RECOMMENDATIONS,
    RULES_FOR_GETTING_TO_KNOW_PET,
    DOCUMENTS_FOR_ADOPTION_PET,
    ANIMAL_TRANSPORTATION,
    HOUSE_FOR_CUB,
    HOUSE_FOR_ADULT_PET,
    HOUSE_FOR_DISABLED_PET,
    REASONS_FOR_REFUSAL_OF_ADOPTION,
    TIPS_FROM_DOG_HANDLER,
    RECOMMENDED_DOG_HANDLERS
}
